### ISSUE TITLE
Description for each variable

### ISSUE THREAD

**Issue by sujeongsong** [BiomedSciAI/causallib#63]
Hello, thank you for providing such valuable materials. 

I am writing to ask you a question on ACIC2016 dataset. 
I am searching for the description for each variable of covariate data, such as mother's age, baby's head circumference, etc. 
Could you let me know where I can find it? 

Many thanks in advance.

**Comment by ehudkr** [comment]
Hi, apologies for my late reply.

According to their [paper](https://projecteuclid.org/journals/statistical-science/volume-34/issue-1/Automated-versus-Do-It-Yourself-Methods-for-Causal-Inference/10.1214/18-STS667.full), the 2016 ACIC data challenge organizers picked a subset of covariates that deemed relevant (section 4.2). 
However, because the treatment mechanism and the outcome response surface are synthetically simulated "blindly" from that point onward (i.e., there's no special considerations for specific covariates like age or sex, etc.), I believe they were deliberately masked (replaced by x1, x2...). 
Regardless, I skimmed the [2016 ACIC data generation repo](https://github.com/vdorie/aciccomp/tree/master/2016) and found [this list named of 58 covariates](https://github.com/vdorie/aciccomp/blob/master/2016/man/input_2016.Rd). Not quite a description book, but most names are relatively clear. I assume their order in that list correspond to the order of columns, but I have not thoroughly checked it. 

I hope this answers it. Please let me know if you have any more questions.
